;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	dabbrev-expand
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-colon
	c-electric-delete-forward
	mouse-save-then-kill
	mouse-set-region
	))
